---
  header_logo_url:  http://Coeorrhyncha.archive.speciesfile.org/HomePage/Coleorrhyncha/img_Logo/SiteLogo.jpg
  header_logo_text: Coleorrhyncha Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
