---
metadata:
  - name: description
    content: The Coleorrhyncha Species File is a taxonomic, nomenclatural, and bibliographic database of the moss bugs of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, Species File Group, Coleorrhyncha, moss bugs, taxonpages, Coleorrhyncha Species File
  - name: robots
    content: follow
