---
  project_name: "Coleorryncha Species File"
  project_citation: "Coleorrhyncha Species File"
  project_authors: "Heads, S.W., Hopkins, H. & Maehr, M.D."
  project_url: "https://coleorryhncha.speciesfile.org"
  project_old_url: "https://coleorryhncha.archive.speciesfile.org" 
  focal_taxon: "coleorryncha"
  focal_taxon_common_name: "moss bugs"
  contact_email: "cockroachdoc@gmail.com"
